#!/bin/bash

VERSION="v0.1.0"
HOSTSOURCESLIST=(
	"yhosts | https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts"
	"大圣净化 | https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts"
	"1024hosts | https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts"
	"StevenBlackhosts | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
)
RULESOURCESLIST=(
	"oisd | https://small.oisd.nl"
 	"antiAdForAdGuard1 | https://anti-ad.net/adguard.txt"
	"antiAdForAdGuard2 | https://anti-ad.net/easylist.txt"
	"Hblock | https://hblock.molinero.dev/hosts_adblock.txt"
	"EasyList | https://easylist-downloads.adblockplus.org/easylist.txt"
	"dont-care-about-cookies | https://www.i-dont-care-about-cookies.eu/abp/"
	"EasyListChina | https://easylist-downloads.adblockplus.org/easylistchina.txt"
	"EasyListPrivacy | https://easylist-downloads.adblockplus.org/easyprivacy.txt"
	"AdGuardDNS | https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
	"AdRulesDNSList | https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt"
	"1Hosts | https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/adblock.txt"
	"d3host | https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock"
	"乘风视频 | https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt"
	"乘风通用 | https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt"
	"antiadblockfilters | https://easylist-downloads.adblockplus.org/antiadblockfilters.txt"
	"NEODEVHOST | https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker"
	"cjxlistAnnoyance | https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt"
	"SmartTVAGH | https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt"
	"NoAppDownload | https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt"
	"AWAvenue | https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt"
	"AdGuardBase | https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt"
	"AdGuardChinese | https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt"
	"AdguardFiltersGermanAllow | https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/GermanFilter/sections/allowlist.txt"
	"AdguardFiltersChineseAllow | https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/allowlist.txt"
	"AdguardFiltersTurkishAllow | https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/TurkishFilter/sections/allowlist.txt"
	"AdguardFiltersSpywareAllow | https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/allowlist.txt"
)
